### ISSUE TITLE
The service didn't respond

### ISSUE THREAD

**Issue by archx** [hantsy/vertx-sandbox#1361]
In the 'kotlin-co' example, when I tried accessing the API `/posts`, the service didn't respond. not sure if it's an issue with coroutines.

**Comment by hantsy** [comment]
Thanks for reporting this issue, it is caused a former refactoring because coroutines handler is ugly. 

I tried to move the coHanlder to standalone coroutinesScope fun, it did not work, as you encountered, revert to use private fun, and remove the `coroutinesScope` https://github.com/hantsy/vertx-sandbox/blob/master/kotlin-co/src/main/kotlin/com/example/demo/MainVerticle.kt#L168

I am not an expert of both Vertx and Coroutines,  really confused about the context switch between vertx and coroutines.

I think in the next 4.5, it will include the official solution. https://github.com/vert-x3/vertx-lang-kotlin/issues/194#issuecomment-1768894804

**Comment by hantsy** [comment]
The codes is cleaned, and working now.
